Repository target/captains-log, pull requests merged in 2018-10, with the labels that each got.

#17 Add Documentation Using Docsify
  README.md
  docs/.nojekyll
  docs/README.md
  docs/_sidebar.md
  docs/code-of-conduct/README.md
  docs/configuration/README.md
  docs/contributing/README.md
  docs/examples/README.md
  docs/index.html
  docs/static/example-output.png
Labels: enhancement, good first issue, help wanted

#14 feat: Implement Ticket Finders (e.g. Github Issues)
  .gitignore
  .nvmrc
  Dockerfile
  config/test.json
  src/config.js
  src/facades/ReleaseCommunicationFacade.js
  src/facades/__tests__/ReleaseCommunicationFacade.test.js
  src/factories/Message/generate.js
  src/factories/Message/index.js
  src/factories/Team/IssueTracker.js
  src/factories/Team/__tests__/IssueTracker.test.js
  src/factories/Team/__tests__/Team.test.js
  src/factories/Team/index.js
  src/index.js
  src/utils/__fixtures__/messagesToFormat.js
  src/utils/__tests__/formatMessages.test.js
  src/utils/__tests__/nameSort.test.js
  src/utils/formatMessages.js
  src/utils/index.js
  src/utils/nameSort.js
  src/utils/populateMessages.js
  src/utils/ticketFinder/__fixtures__/mockBody.js
  src/utils/ticketFinder/__tests__/ticketFinder.test.js
  src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js
  src/utils/ticketFinder/finders/github/index.js
  src/utils/ticketFinder/finders/jira/index.js
  src/utils/ticketFinder/index.js
  src/utils/truncate.js
Labels: enhancement

#21 Slack Formatting Whitespace Fix
  src/factories/Team/__tests__/Team.test.js
  src/factories/Team/index.js
Labels: bug

#22 fix: update Jira issue regex to no leading number
  src/utils/ticketFinder/__fixtures__/mockBody.js
  src/utils/ticketFinder/finders/jira/index.js
Labels: bug

#24 Add Slack Message Formatting Url To Console Output
  src/index.js
  src/utils/__tests__/generateSlackFormatterUrl.test.js
  src/utils/generateSlackFormatterUrl.js
  src/utils/index.js
Labels: enhancement
