Repository target/captains-log, pull requests merged in 2020-10, with the labels that each got.

#81 feat: Use Slack Blocks
  .eslintignore
  .gitignore
  index.js
  package.json
  src/config.js
  src/constants/index.js
  src/facades/ReleaseCommunicationFacade.js
  src/facades/__tests__/ReleaseCommunicationFacade.test.js
  src/factories/Blocks/divider.js
  src/factories/Blocks/header.js
  src/factories/Blocks/section.js
  src/factories/Message/__tests__/Message.test.js
  src/factories/Message/generate.js
  src/factories/Team/__tests__/Team.test.js
  src/factories/Team/index.js
  src/handlers/postMessageHandler.js
  src/index.js
  src/utils/__tests__/formatMessages.test.js
  src/utils/__tests__/generateSlackFormatterUrl.test.js
  src/utils/__tests__/populateMessages.test.js
  src/utils/__tests__/prepareBlocks.test.js
  src/utils/__tests__/sendMessages.test.js
  src/utils/formatMessages.js
  src/utils/generateSlackFormatterUrl.js
  src/utils/index.js
  src/utils/initializeCaptainsConfig.js
  src/utils/populateMessages.js
  src/utils/prepareBlocks.js
  src/utils/sendMessages.js
  yarn.lock
Labels: :sparkles: feat, dependencies, 🚨 tests

#84 fix: typo, retreive -> retrieve
  src/facades/ReleaseCommunicationFacade.js
Labels: :wastebasket: chore

#83 fix: Assert Message Order
  src/utils/sendMessages.js
Labels: :bug: fix

#85 chore: Update Docker
  Dockerfile
Labels: :wastebasket: chore

#86 fix: Incorrect Github Regex
  src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js
  src/utils/ticketFinder/finders/github/index.js
Labels: :bug: fix, 🧟‍♀️ hacktoberfest-accepted

#88 refactor: enhance github url regex
  src/utils/ticketFinder/finders/github/__tests__/githubFinder.test.js
  src/utils/ticketFinder/finders/github/index.js
Labels: :bug: fix, :package: refactor, :sparkles: feat
